Feature/dfs 38 latest activity
DFS-Swiss/dfs-neo pull request #26
Opened 2022-07-20 08:55 UTC by AnHere

2022-07-20 10:28 UTC, TilDoesCode requested changes

2022-07-20 10:28 UTC, TilDoesCode commented on lib/hooks/use_user_asset_data.dart
> +DataContainer<InvestmentData> useInvestmentData(String symbol) {
rename to useUserAssetsForSymbol to better line up with the naming of other hooks

2022-07-20 10:28 UTC, TilDoesCode commented on lib/services/stockinvestment_service.dart
> +class StockInvestmentUtil {
Could be redundant with logic I implemented for the portfolio screen. We will have to check this later.

2022-07-20 10:28 UTC, TilDoesCode commented on lib/widgets/filter/valuefilter_widget.dart
> +  final Object currentValue;
Type this

2022-07-21 15:35 UTC, AnHere commented on lib/widgets/filter/valuefilter_widget.dart
> +  final Object currentValue;
I dont get it. "final this value"?

2022-07-21 15:36 UTC, AnHere commented on lib/widgets/cards/open_order_card.dart
> +// ignore: must_be_immutable
What do you mean? Do I need to remove this comment? I guess it is not my implementation, I only moved the file :D

2022-07-24 14:32 UTC, TilDoesCode approved these changes

2022-07-24 14:33 UTC, merged