settings migrated to new pattern
DFS-Swiss/dfs-neo pull request #73
Opened 2022-09-07 14:05 UTC by TilDoesCode

2022-09-12 00:02 UTC, AnHere requested changes
Looks great! One small adjustment an one question to answer

2022-09-12 00:02 UTC, AnHere commented on lib/hooks/use_balance_hidden.dart
> +      state.value = locator<SettingsService>().hideBalanceSettings.getValue();
Please inject the locator just once at the beginning (line 6) and then use the reference

2022-09-12 00:02 UTC, AnHere commented on lib/services/settings/settings_service.dart
> +  late final ThemeSettingsProvider themeSettings;
Really really good!

2022-09-12 00:02 UTC, AnHere commented on lib/main.dart
> +  locator<SettingsService>().init().then((value) {
Why do we need to initialize the SettingsService first?

2022-09-14 09:11 UTC, TilDoesCode commented on lib/main.dart
> +  locator<SettingsService>().init().then((value) {
Because some relatively top-level system needs it. Its not beautiful but necessary

2022-09-14 09:12 UTC, TilDoesCode commented on lib/services/settings/settings_service.dart
> +  late final ThemeSettingsProvider themeSettings;
Thanks!

2022-09-15 08:13 UTC, AnHere commented on lib/main.dart
> +  locator<SettingsService>().init().then((value) {
Do you remember which top-level system? I guess it will be helpful someday, if we leave a litte comment in the code in this case

2022-09-15 08:17 UTC, TilDoesCode commented on lib/main.dart
> +  locator<SettingsService>().init().then((value) {
Line 38, useBrightness for the theme requires the settings service

2022-09-15 08:18 UTC, TilDoesCode commented on lib/hooks/use_balance_hidden.dart
> +      state.value = locator<SettingsService>().hideBalanceSettings.getValue();
Correct!

2022-09-19 01:35 UTC, AnHere approved these changes

2022-09-19 01:38 UTC, merged